package server

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"net"
	"os"
	"path/filepath"
	"testing"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/status"
	"gorm.io/gorm"

	myfwv1 "iptables-tool/api/myfw/v1"
	"iptables-tool/internal/config"
	"iptables-tool/internal/db"
)

// findCA locates the dev-ca directory generated by scripts/gen-ca.sh, walking
// up from the test's working directory. Skips the test if not present.
func findCA(t *testing.T) string {
	t.Helper()
	dir, _ := os.Getwd()
	for i := 0; i < 5; i++ {
		candidate := filepath.Join(dir, "dev-ca")
		if _, err := os.Stat(filepath.Join(candidate, "ca.pem")); err == nil {
			return candidate
		}
		dir = filepath.Dir(dir)
	}
	t.Skip("dev-ca not found; run `make gen-ca` to enable mTLS tests")
	return ""
}

// startTestServer boots a full Server (gRPC + interceptors) on a random port
// and returns the gRPC address, the loaded config, and the shared *gorm.DB so
// tests can also hit the Web handler against the same DB via httptest.
func startTestServer(t *testing.T) (grpcAddr string, cfg config.Config, gdb *gorm.DB) {
	t.Helper()
	caDir := findCA(t)

	cfg = config.Default()
	// Ephemeral, per-test SQLite so migrations don't collide.
	t.Setenv("MYFW_DB_DRIVER", "sqlite")
	t.Setenv("MYFW_DB_DSN", filepath.Join(t.TempDir(), "srv.db"))
	gdb, err := db.OpenFromEnv()
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	if err := db.Migrate(gdb); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	cfg.Server.Web.Listen = "127.0.0.1:0"
	cfg.Server.GRPC.Listen = "127.0.0.1:0"
	cfg.Server.GRPC.TLS = config.TLSConfig{
		CAFile:   filepath.Join(caDir, "ca.pem"),
		CertFile: filepath.Join(caDir, "server.crt"),
		KeyFile:  filepath.Join(caDir, "server.key"),
	}
	cfg.CA = config.CAConfig{
		CertFile:     filepath.Join(caDir, "ca.pem"),
		KeyFile:      filepath.Join(caDir, "ca.key"),
		AgentCertTTL: time.Hour,
	}
	cfg.Bootstrap.TokenTTL = 15 * time.Minute

	srv, err := New(cfg, testLogger(), gdb)
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	// Bind a real listener for gRPC so we know the actual port.
	ln, err := net.Listen("tcp", cfg.Server.GRPC.Listen)
	if err != nil {
		t.Fatal(err)
	}
	go func() { _ = srv.grpc.Serve(ln) }()
	t.Cleanup(srv.grpc.Stop)

	return ln.Addr().String(), cfg, gdb
}

// TestGRPCRequiresClientCert verifies that RPCs NOT in bootstrapMethods are
// rejected without a client certificate, and accepted with one signed by our
// CA. This is the mTLS guarantee the design requires; the "reject" now
// happens at the auth interceptor layer since we allow bootstrap RPCs to run
// on TLS without a client cert.
func TestGRPCRequiresClientCert(t *testing.T) {
	addr, cfg, _ := startTestServer(t)
	pool := caPool(t, cfg.Server.GRPC.TLS.CAFile)

	t.Run("non_bootstrap_method_without_cert_rejected", func(t *testing.T) {
		conn, err := grpc.NewClient(addr,
			grpc.WithTransportCredentials(credentials.NewTLS(&tls.Config{
				RootCAs:    pool,
				ServerName: "localhost",
			})),
		)
		if err != nil {
			t.Fatal(err)
		}
		defer conn.Close()

		// RenewCert is NOT in bootstrapMethods, so it must be rejected without a cert.
		client := myfwv1.NewRegistrationClient(conn)
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		_, err = client.RenewCert(ctx, &myfwv1.RenewCertRequest{NodeId: "x"})
		if err == nil {
			t.Fatal("expected auth error, got nil")
		}
		if got := status.Code(err); got != codes.Unauthenticated {
			t.Fatalf("want Unauthenticated, got %v: %v", got, err)
		}
	})
}

// caPool loads a CA cert into an x509 pool for a client tls.Config.
func caPool(t *testing.T, path string) *x509.CertPool {
	t.Helper()
	caPEM, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		t.Fatal("no certs in CA file")
	}
	return pool
}
