// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: myfw/v1/common.proto

package myfwv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction of a firewall policy/rule relative to the host.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_INBOUND     Direction = 1 // INPUT
	Direction_DIRECTION_OUTBOUND    Direction = 2 // OUTPUT
	Direction_DIRECTION_FORWARD     Direction = 3 // FORWARD
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_INBOUND",
		2: "DIRECTION_OUTBOUND",
		3: "DIRECTION_FORWARD",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_INBOUND":     1,
		"DIRECTION_OUTBOUND":    2,
		"DIRECTION_FORWARD":     3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_myfw_v1_common_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_myfw_v1_common_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{0}
}

// Transport / network protocol a rule matches.
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_ANY         Protocol = 1
	Protocol_PROTOCOL_TCP         Protocol = 2
	Protocol_PROTOCOL_UDP         Protocol = 3
	Protocol_PROTOCOL_ICMP        Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_ANY",
		2: "PROTOCOL_TCP",
		3: "PROTOCOL_UDP",
		4: "PROTOCOL_ICMP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_ANY":         1,
		"PROTOCOL_TCP":         2,
		"PROTOCOL_UDP":         3,
		"PROTOCOL_ICMP":        4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_myfw_v1_common_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_myfw_v1_common_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{1}
}

// Terminal action applied to a matched packet.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_ACCEPT      Action = 1
	Action_ACTION_DROP        Action = 2
	Action_ACTION_REJECT      Action = 3
	Action_ACTION_MARK        Action = 4 // mangle MARK
	Action_ACTION_DNAT        Action = 5
	Action_ACTION_SNAT        Action = 6
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ACCEPT",
		2: "ACTION_DROP",
		3: "ACTION_REJECT",
		4: "ACTION_MARK",
		5: "ACTION_DNAT",
		6: "ACTION_SNAT",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ACCEPT":      1,
		"ACTION_DROP":        2,
		"ACTION_REJECT":      3,
		"ACTION_MARK":        4,
		"ACTION_DNAT":        5,
		"ACTION_SNAT":        6,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_myfw_v1_common_proto_enumTypes[2].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_myfw_v1_common_proto_enumTypes[2]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{2}
}

// Which firewall backend an Agent selected for a node.
type FirewallBackend int32

const (
	FirewallBackend_FIREWALL_BACKEND_UNSPECIFIED     FirewallBackend = 0
	FirewallBackend_FIREWALL_BACKEND_IPTABLES_LEGACY FirewallBackend = 1
	FirewallBackend_FIREWALL_BACKEND_IPTABLES_NFT    FirewallBackend = 2 // iptables with the nft backend
	FirewallBackend_FIREWALL_BACKEND_NFTABLES        FirewallBackend = 3 // native nftables
)

// Enum value maps for FirewallBackend.
var (
	FirewallBackend_name = map[int32]string{
		0: "FIREWALL_BACKEND_UNSPECIFIED",
		1: "FIREWALL_BACKEND_IPTABLES_LEGACY",
		2: "FIREWALL_BACKEND_IPTABLES_NFT",
		3: "FIREWALL_BACKEND_NFTABLES",
	}
	FirewallBackend_value = map[string]int32{
		"FIREWALL_BACKEND_UNSPECIFIED":     0,
		"FIREWALL_BACKEND_IPTABLES_LEGACY": 1,
		"FIREWALL_BACKEND_IPTABLES_NFT":    2,
		"FIREWALL_BACKEND_NFTABLES":        3,
	}
)

func (x FirewallBackend) Enum() *FirewallBackend {
	p := new(FirewallBackend)
	*p = x
	return p
}

func (x FirewallBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_myfw_v1_common_proto_enumTypes[3].Descriptor()
}

func (FirewallBackend) Type() protoreflect.EnumType {
	return &file_myfw_v1_common_proto_enumTypes[3]
}

func (x FirewallBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallBackend.Descriptor instead.
func (FirewallBackend) EnumDescriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{3}
}

// Capabilities probed by the Agent at startup (see design.md § 5).
type Capability struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Distro            string                 `protobuf:"bytes,1,opt,name=distro,proto3" json:"distro,omitempty"` // e.g. "ubuntu 22.04"
	KernelVersion     string                 `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	IptablesVersion   string                 `protobuf:"bytes,3,opt,name=iptables_version,json=iptablesVersion,proto3" json:"iptables_version,omitempty"`
	IptablesBackend   FirewallBackend        `protobuf:"varint,4,opt,name=iptables_backend,json=iptablesBackend,proto3,enum=myfw.v1.FirewallBackend" json:"iptables_backend,omitempty"`
	NftSupported      bool                   `protobuf:"varint,5,opt,name=nft_supported,json=nftSupported,proto3" json:"nft_supported,omitempty"`
	DockerPresent     bool                   `protobuf:"varint,6,opt,name=docker_present,json=dockerPresent,proto3" json:"docker_present,omitempty"`
	KubernetesPresent bool                   `protobuf:"varint,7,opt,name=kubernetes_present,json=kubernetesPresent,proto3" json:"kubernetes_present,omitempty"`
	SelectedBackend   FirewallBackend        `protobuf:"varint,8,opt,name=selected_backend,json=selectedBackend,proto3,enum=myfw.v1.FirewallBackend" json:"selected_backend,omitempty"` // the driver the Agent chose
	Extra             []string               `protobuf:"bytes,9,rep,name=extra,proto3" json:"extra,omitempty"`                                                                          // free-form probe notes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_myfw_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetDistro() string {
	if x != nil {
		return x.Distro
	}
	return ""
}

func (x *Capability) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *Capability) GetIptablesVersion() string {
	if x != nil {
		return x.IptablesVersion
	}
	return ""
}

func (x *Capability) GetIptablesBackend() FirewallBackend {
	if x != nil {
		return x.IptablesBackend
	}
	return FirewallBackend_FIREWALL_BACKEND_UNSPECIFIED
}

func (x *Capability) GetNftSupported() bool {
	if x != nil {
		return x.NftSupported
	}
	return false
}

func (x *Capability) GetDockerPresent() bool {
	if x != nil {
		return x.DockerPresent
	}
	return false
}

func (x *Capability) GetKubernetesPresent() bool {
	if x != nil {
		return x.KubernetesPresent
	}
	return false
}

func (x *Capability) GetSelectedBackend() FirewallBackend {
	if x != nil {
		return x.SelectedBackend
	}
	return FirewallBackend_FIREWALL_BACKEND_UNSPECIFIED
}

func (x *Capability) GetExtra() []string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Stable identity + machine fingerprint captured at registration
// (see design.md § 13.3).
type MachineFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // /etc/machine-id
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"` // GOARCH-style, e.g. "amd64"
	MacAddresses  []string               `protobuf:"bytes,5,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,6,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineFingerprint) Reset() {
	*x = MachineFingerprint{}
	mi := &file_myfw_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineFingerprint) ProtoMessage() {}

func (x *MachineFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineFingerprint.ProtoReflect.Descriptor instead.
func (*MachineFingerprint) Descriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *MachineFingerprint) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *MachineFingerprint) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineFingerprint) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *MachineFingerprint) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *MachineFingerprint) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

func (x *MachineFingerprint) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

// Timestamp is a UTC point in time independent of any local calendar.
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_myfw_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_myfw_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_myfw_v1_common_proto protoreflect.FileDescriptor

const file_myfw_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x14myfw/v1/common.proto\x12\amyfw.v1\"\x91\x03\n" +
	"\n" +
	"Capability\x12\x16\n" +
	"\x06distro\x18\x01 \x01(\tR\x06distro\x12%\n" +
	"\x0ekernel_version\x18\x02 \x01(\tR\rkernelVersion\x12)\n" +
	"\x10iptables_version\x18\x03 \x01(\tR\x0fiptablesVersion\x12C\n" +
	"\x10iptables_backend\x18\x04 \x01(\x0e2\x18.myfw.v1.FirewallBackendR\x0fiptablesBackend\x12#\n" +
	"\rnft_supported\x18\x05 \x01(\bR\fnftSupported\x12%\n" +
	"\x0edocker_present\x18\x06 \x01(\bR\rdockerPresent\x12-\n" +
	"\x12kubernetes_present\x18\a \x01(\bR\x11kubernetesPresent\x12C\n" +
	"\x10selected_backend\x18\b \x01(\x0e2\x18.myfw.v1.FirewallBackendR\x0fselectedBackend\x12\x14\n" +
	"\x05extra\x18\t \x03(\tR\x05extra\"\xd2\x01\n" +
	"\x12MachineFingerprint\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\rmac_addresses\x18\x05 \x03(\tR\fmacAddresses\x12!\n" +
	"\fip_addresses\x18\x06 \x03(\tR\vipAddresses\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos*l\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_INBOUND\x10\x01\x12\x16\n" +
	"\x12DIRECTION_OUTBOUND\x10\x02\x12\x15\n" +
	"\x11DIRECTION_FORWARD\x10\x03*m\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_ANY\x10\x01\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x02\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x03\x12\x11\n" +
	"\rPROTOCOL_ICMP\x10\x04*\x8a\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_ACCEPT\x10\x01\x12\x0f\n" +
	"\vACTION_DROP\x10\x02\x12\x11\n" +
	"\rACTION_REJECT\x10\x03\x12\x0f\n" +
	"\vACTION_MARK\x10\x04\x12\x0f\n" +
	"\vACTION_DNAT\x10\x05\x12\x0f\n" +
	"\vACTION_SNAT\x10\x06*\x9b\x01\n" +
	"\x0fFirewallBackend\x12 \n" +
	"\x1cFIREWALL_BACKEND_UNSPECIFIED\x10\x00\x12$\n" +
	" FIREWALL_BACKEND_IPTABLES_LEGACY\x10\x01\x12!\n" +
	"\x1dFIREWALL_BACKEND_IPTABLES_NFT\x10\x02\x12\x1d\n" +
	"\x19FIREWALL_BACKEND_NFTABLES\x10\x03B\"Z iptables-tool/api/myfw/v1;myfwv1b\x06proto3"

var (
	file_myfw_v1_common_proto_rawDescOnce sync.Once
	file_myfw_v1_common_proto_rawDescData []byte
)

func file_myfw_v1_common_proto_rawDescGZIP() []byte {
	file_myfw_v1_common_proto_rawDescOnce.Do(func() {
		file_myfw_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myfw_v1_common_proto_rawDesc), len(file_myfw_v1_common_proto_rawDesc)))
	})
	return file_myfw_v1_common_proto_rawDescData
}

var file_myfw_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_myfw_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_myfw_v1_common_proto_goTypes = []any{
	(Direction)(0),             // 0: myfw.v1.Direction
	(Protocol)(0),              // 1: myfw.v1.Protocol
	(Action)(0),                // 2: myfw.v1.Action
	(FirewallBackend)(0),       // 3: myfw.v1.FirewallBackend
	(*Capability)(nil),         // 4: myfw.v1.Capability
	(*MachineFingerprint)(nil), // 5: myfw.v1.MachineFingerprint
	(*Timestamp)(nil),          // 6: myfw.v1.Timestamp
}
var file_myfw_v1_common_proto_depIdxs = []int32{
	3, // 0: myfw.v1.Capability.iptables_backend:type_name -> myfw.v1.FirewallBackend
	3, // 1: myfw.v1.Capability.selected_backend:type_name -> myfw.v1.FirewallBackend
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_myfw_v1_common_proto_init() }
func file_myfw_v1_common_proto_init() {
	if File_myfw_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myfw_v1_common_proto_rawDesc), len(file_myfw_v1_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myfw_v1_common_proto_goTypes,
		DependencyIndexes: file_myfw_v1_common_proto_depIdxs,
		EnumInfos:         file_myfw_v1_common_proto_enumTypes,
		MessageInfos:      file_myfw_v1_common_proto_msgTypes,
	}.Build()
	File_myfw_v1_common_proto = out.File
	file_myfw_v1_common_proto_goTypes = nil
	file_myfw_v1_common_proto_depIdxs = nil
}
