// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: myfw/v1/registration.proto

package myfwv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	CandidateId    string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"` // Agent-generated candidate node id
	CsrPem         []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                // PKCS#10 CSR; private key never leaves host
	Fingerprint    *MachineFingerprint    `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Capability     *Capability            `protobuf:"bytes,5,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_myfw_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_myfw_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *RegisterRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RegisterRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *RegisterRequest) GetFingerprint() *MachineFingerprint {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *RegisterRequest) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                        // final id assigned by Controller
	ClientCertPem []byte                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"` // signed client certificate
	NodeStatus    string                 `protobuf:"bytes,3,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`            // "PENDING" | "ACTIVE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_myfw_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_myfw_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *RegisterResponse) GetNodeStatus() string {
	if x != nil {
		return x.NodeStatus
	}
	return ""
}

type RenewCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertRequest) Reset() {
	*x = RenewCertRequest{}
	mi := &file_myfw_v1_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertRequest) ProtoMessage() {}

func (x *RenewCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertRequest.ProtoReflect.Descriptor instead.
func (*RenewCertRequest) Descriptor() ([]byte, []int) {
	return file_myfw_v1_registration_proto_rawDescGZIP(), []int{2}
}

func (x *RenewCertRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RenewCertRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RenewCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	NotAfterUnix  int64                  `protobuf:"varint,2,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertResponse) Reset() {
	*x = RenewCertResponse{}
	mi := &file_myfw_v1_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertResponse) ProtoMessage() {}

func (x *RenewCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertResponse.ProtoReflect.Descriptor instead.
func (*RenewCertResponse) Descriptor() ([]byte, []int) {
	return file_myfw_v1_registration_proto_rawDescGZIP(), []int{3}
}

func (x *RenewCertResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *RenewCertResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

var File_myfw_v1_registration_proto protoreflect.FileDescriptor

const file_myfw_v1_registration_proto_rawDesc = "" +
	"\n" +
	"\x1amyfw/v1/registration.proto\x12\amyfw.v1\x1a\x14myfw/v1/common.proto\"\xea\x01\n" +
	"\x0fRegisterRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\x12=\n" +
	"\vfingerprint\x18\x04 \x01(\v2\x1b.myfw.v1.MachineFingerprintR\vfingerprint\x123\n" +
	"\n" +
	"capability\x18\x05 \x01(\v2\x13.myfw.v1.CapabilityR\n" +
	"capability\"t\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\fR\rclientCertPem\x12\x1f\n" +
	"\vnode_status\x18\x03 \x01(\tR\n" +
	"nodeStatus\"D\n" +
	"\x10RenewCertRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\"a\n" +
	"\x11RenewCertResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12$\n" +
	"\x0enot_after_unix\x18\x02 \x01(\x03R\fnotAfterUnix2\x93\x01\n" +
	"\fRegistration\x12?\n" +
	"\bRegister\x12\x18.myfw.v1.RegisterRequest\x1a\x19.myfw.v1.RegisterResponse\x12B\n" +
	"\tRenewCert\x12\x19.myfw.v1.RenewCertRequest\x1a\x1a.myfw.v1.RenewCertResponseB\"Z iptables-tool/api/myfw/v1;myfwv1b\x06proto3"

var (
	file_myfw_v1_registration_proto_rawDescOnce sync.Once
	file_myfw_v1_registration_proto_rawDescData []byte
)

func file_myfw_v1_registration_proto_rawDescGZIP() []byte {
	file_myfw_v1_registration_proto_rawDescOnce.Do(func() {
		file_myfw_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myfw_v1_registration_proto_rawDesc), len(file_myfw_v1_registration_proto_rawDesc)))
	})
	return file_myfw_v1_registration_proto_rawDescData
}

var file_myfw_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_myfw_v1_registration_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: myfw.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 1: myfw.v1.RegisterResponse
	(*RenewCertRequest)(nil),   // 2: myfw.v1.RenewCertRequest
	(*RenewCertResponse)(nil),  // 3: myfw.v1.RenewCertResponse
	(*MachineFingerprint)(nil), // 4: myfw.v1.MachineFingerprint
	(*Capability)(nil),         // 5: myfw.v1.Capability
}
var file_myfw_v1_registration_proto_depIdxs = []int32{
	4, // 0: myfw.v1.RegisterRequest.fingerprint:type_name -> myfw.v1.MachineFingerprint
	5, // 1: myfw.v1.RegisterRequest.capability:type_name -> myfw.v1.Capability
	0, // 2: myfw.v1.Registration.Register:input_type -> myfw.v1.RegisterRequest
	2, // 3: myfw.v1.Registration.RenewCert:input_type -> myfw.v1.RenewCertRequest
	1, // 4: myfw.v1.Registration.Register:output_type -> myfw.v1.RegisterResponse
	3, // 5: myfw.v1.Registration.RenewCert:output_type -> myfw.v1.RenewCertResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_myfw_v1_registration_proto_init() }
func file_myfw_v1_registration_proto_init() {
	if File_myfw_v1_registration_proto != nil {
		return
	}
	file_myfw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myfw_v1_registration_proto_rawDesc), len(file_myfw_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myfw_v1_registration_proto_goTypes,
		DependencyIndexes: file_myfw_v1_registration_proto_depIdxs,
		MessageInfos:      file_myfw_v1_registration_proto_msgTypes,
	}.Build()
	File_myfw_v1_registration_proto = out.File
	file_myfw_v1_registration_proto_goTypes = nil
	file_myfw_v1_registration_proto_depIdxs = nil
}
