// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: myfw/v1/rule.proto

package myfwv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompiledRule is the driver-agnostic intermediate representation produced by
// the Controller's Rule Compiler and consumed by an Agent's Firewall Driver.
// The Agent translates this into concrete iptables / nftables constructs
// inside the MYFW namespace (see design.md § 4 / § 6 / § 7).
type CompiledRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // stable rule id (maps to a policy version)
	Direction        Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=myfw.v1.Direction" json:"direction,omitempty"`
	Source           string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`           // IP or CIDR; empty = any
	Destination      string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"` // IP or CIDR; empty = any
	Protocol         Protocol               `protobuf:"varint,5,opt,name=protocol,proto3,enum=myfw.v1.Protocol" json:"protocol,omitempty"`
	PortRange        string                 `protobuf:"bytes,6,opt,name=port_range,json=portRange,proto3" json:"port_range,omitempty"` // "22", "1000-2000"; empty = any
	Action           Action                 `protobuf:"varint,7,opt,name=action,proto3,enum=myfw.v1.Action" json:"action,omitempty"`
	Mark             uint32                 `protobuf:"varint,8,opt,name=mark,proto3" json:"mark,omitempty"`               // used when action = MARK
	NatTo            string                 `protobuf:"bytes,9,opt,name=nat_to,json=natTo,proto3" json:"nat_to,omitempty"` // used when action = DNAT/SNAT ("ip" or "ip:port")
	Priority         int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`      // lower = evaluated first
	Description      string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	SourceGroup      string                 `protobuf:"bytes,12,opt,name=source_group,json=sourceGroup,proto3" json:"source_group,omitempty"`                // 引用 AddressSet.name,编译为 set 匹配(多 CIDR)
	DestinationGroup string                 `protobuf:"bytes,13,opt,name=destination_group,json=destinationGroup,proto3" json:"destination_group,omitempty"` // 引用 AddressSet.name
	MatchMark        uint32                 `protobuf:"varint,14,opt,name=match_mark,json=matchMark,proto3" json:"match_mark,omitempty"`                     // 匹配条件:已打标(与 action=MARK 打标正交)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompiledRule) Reset() {
	*x = CompiledRule{}
	mi := &file_myfw_v1_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledRule) ProtoMessage() {}

func (x *CompiledRule) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledRule.ProtoReflect.Descriptor instead.
func (*CompiledRule) Descriptor() ([]byte, []int) {
	return file_myfw_v1_rule_proto_rawDescGZIP(), []int{0}
}

func (x *CompiledRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompiledRule) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *CompiledRule) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompiledRule) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CompiledRule) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CompiledRule) GetPortRange() string {
	if x != nil {
		return x.PortRange
	}
	return ""
}

func (x *CompiledRule) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *CompiledRule) GetMark() uint32 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *CompiledRule) GetNatTo() string {
	if x != nil {
		return x.NatTo
	}
	return ""
}

func (x *CompiledRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CompiledRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompiledRule) GetSourceGroup() string {
	if x != nil {
		return x.SourceGroup
	}
	return ""
}

func (x *CompiledRule) GetDestinationGroup() string {
	if x != nil {
		return x.DestinationGroup
	}
	return ""
}

func (x *CompiledRule) GetMatchMark() uint32 {
	if x != nil {
		return x.MatchMark
	}
	return 0
}

// RuleSet is the full desired state for a node's MYFW namespace at a given
// policy version. Apply is all-or-nothing against this set.
type RuleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // monotonic policy version
	Rules         []*CompiledRule        `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,4,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"` // hash of the normalized set, for drift checks
	Sets          []*AddressSet          `protobuf:"bytes,5,rep,name=sets,proto3" json:"sets,omitempty"`                                     // 期望地址组态,随版本原子下发到 Agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSet) Reset() {
	*x = RuleSet{}
	mi := &file_myfw_v1_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSet) ProtoMessage() {}

func (x *RuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSet.ProtoReflect.Descriptor instead.
func (*RuleSet) Descriptor() ([]byte, []int) {
	return file_myfw_v1_rule_proto_rawDescGZIP(), []int{1}
}

func (x *RuleSet) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RuleSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleSet) GetRules() []*CompiledRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *RuleSet) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *RuleSet) GetSets() []*AddressSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

// AddressSet 是下发给 Agent 的地址组期望态:一个组对应节点上的一个 ipset / nft set
// (MYFW-<name>),Policy 通过 source_group / destination_group 引用其名称。
type AddressSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // whitelist / blacklist / 自定义,节点集合名 MYFW-<name>
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`       // whitelist | blacklist | custom
	Members       []string               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"` // CIDR 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressSet) Reset() {
	*x = AddressSet{}
	mi := &file_myfw_v1_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSet) ProtoMessage() {}

func (x *AddressSet) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSet.ProtoReflect.Descriptor instead.
func (*AddressSet) Descriptor() ([]byte, []int) {
	return file_myfw_v1_rule_proto_rawDescGZIP(), []int{2}
}

func (x *AddressSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddressSet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AddressSet) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_myfw_v1_rule_proto protoreflect.FileDescriptor

const file_myfw_v1_rule_proto_rawDesc = "" +
	"\n" +
	"\x12myfw/v1/rule.proto\x12\amyfw.v1\x1a\x14myfw/v1/common.proto\"\xd9\x03\n" +
	"\fCompiledRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x12.myfw.v1.DirectionR\tdirection\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12-\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\x11.myfw.v1.ProtocolR\bprotocol\x12\x1d\n" +
	"\n" +
	"port_range\x18\x06 \x01(\tR\tportRange\x12'\n" +
	"\x06action\x18\a \x01(\x0e2\x0f.myfw.v1.ActionR\x06action\x12\x12\n" +
	"\x04mark\x18\b \x01(\rR\x04mark\x12\x15\n" +
	"\x06nat_to\x18\t \x01(\tR\x05natTo\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12!\n" +
	"\fsource_group\x18\f \x01(\tR\vsourceGroup\x12+\n" +
	"\x11destination_group\x18\r \x01(\tR\x10destinationGroup\x12\x1d\n" +
	"\n" +
	"match_mark\x18\x0e \x01(\rR\tmatchMark\"\xb7\x01\n" +
	"\aRuleSet\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12+\n" +
	"\x05rules\x18\x03 \x03(\v2\x15.myfw.v1.CompiledRuleR\x05rules\x12#\n" +
	"\rexpected_hash\x18\x04 \x01(\tR\fexpectedHash\x12'\n" +
	"\x04sets\x18\x05 \x03(\v2\x13.myfw.v1.AddressSetR\x04sets\"N\n" +
	"\n" +
	"AddressSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembersB\"Z iptables-tool/api/myfw/v1;myfwv1b\x06proto3"

var (
	file_myfw_v1_rule_proto_rawDescOnce sync.Once
	file_myfw_v1_rule_proto_rawDescData []byte
)

func file_myfw_v1_rule_proto_rawDescGZIP() []byte {
	file_myfw_v1_rule_proto_rawDescOnce.Do(func() {
		file_myfw_v1_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myfw_v1_rule_proto_rawDesc), len(file_myfw_v1_rule_proto_rawDesc)))
	})
	return file_myfw_v1_rule_proto_rawDescData
}

var file_myfw_v1_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_myfw_v1_rule_proto_goTypes = []any{
	(*CompiledRule)(nil), // 0: myfw.v1.CompiledRule
	(*RuleSet)(nil),      // 1: myfw.v1.RuleSet
	(*AddressSet)(nil),   // 2: myfw.v1.AddressSet
	(Direction)(0),       // 3: myfw.v1.Direction
	(Protocol)(0),        // 4: myfw.v1.Protocol
	(Action)(0),          // 5: myfw.v1.Action
}
var file_myfw_v1_rule_proto_depIdxs = []int32{
	3, // 0: myfw.v1.CompiledRule.direction:type_name -> myfw.v1.Direction
	4, // 1: myfw.v1.CompiledRule.protocol:type_name -> myfw.v1.Protocol
	5, // 2: myfw.v1.CompiledRule.action:type_name -> myfw.v1.Action
	0, // 3: myfw.v1.RuleSet.rules:type_name -> myfw.v1.CompiledRule
	2, // 4: myfw.v1.RuleSet.sets:type_name -> myfw.v1.AddressSet
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_myfw_v1_rule_proto_init() }
func file_myfw_v1_rule_proto_init() {
	if File_myfw_v1_rule_proto != nil {
		return
	}
	file_myfw_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myfw_v1_rule_proto_rawDesc), len(file_myfw_v1_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myfw_v1_rule_proto_goTypes,
		DependencyIndexes: file_myfw_v1_rule_proto_depIdxs,
		MessageInfos:      file_myfw_v1_rule_proto_msgTypes,
	}.Build()
	File_myfw_v1_rule_proto = out.File
	file_myfw_v1_rule_proto_goTypes = nil
	file_myfw_v1_rule_proto_depIdxs = nil
}
