// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: myfw/v1/stream.proto

package myfwv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentToController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentToController_Heartbeat
	//	*AgentToController_TaskResult
	//	*AgentToController_Drift
	//	*AgentToController_State
	//	*AgentToController_Sync
	Payload       isAgentToController_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToController) Reset() {
	*x = AgentToController{}
	mi := &file_myfw_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToController) ProtoMessage() {}

func (x *AgentToController) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToController.ProtoReflect.Descriptor instead.
func (*AgentToController) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToController) GetPayload() isAgentToController_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentToController) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToController) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentToController) GetDrift() *DriftReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Drift); ok {
			return x.Drift
		}
	}
	return nil
}

func (x *AgentToController) GetState() *StateReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *AgentToController) GetSync() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

type isAgentToController_Payload interface {
	isAgentToController_Payload()
}

type AgentToController_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentToController_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentToController_Drift struct {
	Drift *DriftReport `protobuf:"bytes,3,opt,name=drift,proto3,oneof"`
}

type AgentToController_State struct {
	State *StateReport `protobuf:"bytes,4,opt,name=state,proto3,oneof"`
}

type AgentToController_Sync struct {
	Sync *SyncRequest `protobuf:"bytes,5,opt,name=sync,proto3,oneof"`
}

func (*AgentToController_Heartbeat) isAgentToController_Payload() {}

func (*AgentToController_TaskResult) isAgentToController_Payload() {}

func (*AgentToController_Drift) isAgentToController_Payload() {}

func (*AgentToController_State) isAgentToController_Payload() {}

func (*AgentToController_Sync) isAgentToController_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,3,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"` // hash of the live MYFW namespace
	Capability    *Capability            `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`                      // resent on change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_myfw_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *Heartbeat) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *Heartbeat) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResultHash    string                 `protobuf:"bytes,4,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"` // MYFW hash after applying
	TsUnix        int64                  `protobuf:"varint,5,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_myfw_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResult) GetResultHash() string {
	if x != nil {
		return x.ResultHash
	}
	return ""
}

func (x *TaskResult) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

// DriftReport is emitted by the Watchdog when the live MYFW namespace no
// longer matches the expected hash (see design.md § 12).
type DriftReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	ActualHash    string                 `protobuf:"bytes,3,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	TsUnix        int64                  `protobuf:"varint,5,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftReport) Reset() {
	*x = DriftReport{}
	mi := &file_myfw_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftReport) ProtoMessage() {}

func (x *DriftReport) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftReport.ProtoReflect.Descriptor instead.
func (*DriftReport) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *DriftReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DriftReport) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *DriftReport) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

func (x *DriftReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *DriftReport) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

// StateReport carries periodic network telemetry (see design.md § 14).
type StateReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TsUnix         int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Interfaces     []*InterfaceStat       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	ConntrackCount uint64                 `protobuf:"varint,4,opt,name=conntrack_count,json=conntrackCount,proto3" json:"conntrack_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateReport) Reset() {
	*x = StateReport{}
	mi := &file_myfw_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReport) ProtoMessage() {}

func (x *StateReport) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReport.ProtoReflect.Descriptor instead.
func (*StateReport) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StateReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateReport) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *StateReport) GetInterfaces() []*InterfaceStat {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *StateReport) GetConntrackCount() uint64 {
	if x != nil {
		return x.ConntrackCount
	}
	return 0
}

type InterfaceStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStat) Reset() {
	*x = InterfaceStat{}
	mi := &file_myfw_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStat) ProtoMessage() {}

func (x *InterfaceStat) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStat.ProtoReflect.Descriptor instead.
func (*InterfaceStat) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStat) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceStat) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceStat) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceStat) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

type ControllerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerToAgent_Apply
	//	*ControllerToAgent_Confirm
	//	*ControllerToAgent_Rollback
	//	*ControllerToAgent_Sync
	//	*ControllerToAgent_Ack
	Payload       isControllerToAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerToAgent) Reset() {
	*x = ControllerToAgent{}
	mi := &file_myfw_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerToAgent) ProtoMessage() {}

func (x *ControllerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerToAgent.ProtoReflect.Descriptor instead.
func (*ControllerToAgent) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{6}
}

func (x *ControllerToAgent) GetPayload() isControllerToAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerToAgent) GetApply() *ApplyTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *ControllerToAgent) GetConfirm() *ConfirmTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *ControllerToAgent) GetRollback() *RollbackTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *ControllerToAgent) GetSync() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *ControllerToAgent) GetAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isControllerToAgent_Payload interface {
	isControllerToAgent_Payload()
}

type ControllerToAgent_Apply struct {
	Apply *ApplyTask `protobuf:"bytes,1,opt,name=apply,proto3,oneof"`
}

type ControllerToAgent_Confirm struct {
	Confirm *ConfirmTask `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

type ControllerToAgent_Rollback struct {
	Rollback *RollbackTask `protobuf:"bytes,3,opt,name=rollback,proto3,oneof"`
}

type ControllerToAgent_Sync struct {
	Sync *SyncRequest `protobuf:"bytes,4,opt,name=sync,proto3,oneof"`
}

type ControllerToAgent_Ack struct {
	Ack *HeartbeatAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*ControllerToAgent_Apply) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Confirm) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Rollback) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Sync) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Ack) isControllerToAgent_Payload() {}

// ApplyTask instructs the Agent to snapshot, then converge its MYFW namespace
// to the given RuleSet, then wait for a ConfirmTask within confirm_deadline
// (else auto-rollback). See design.md § 11.
type ApplyTask struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleSet             *RuleSet               `protobuf:"bytes,2,opt,name=rule_set,json=ruleSet,proto3" json:"rule_set,omitempty"`
	ConfirmDeadlineUnix int64                  `protobuf:"varint,3,opt,name=confirm_deadline_unix,json=confirmDeadlineUnix,proto3" json:"confirm_deadline_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyTask) Reset() {
	*x = ApplyTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTask) ProtoMessage() {}

func (x *ApplyTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTask.ProtoReflect.Descriptor instead.
func (*ApplyTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApplyTask) GetRuleSet() *RuleSet {
	if x != nil {
		return x.RuleSet
	}
	return nil
}

func (x *ApplyTask) GetConfirmDeadlineUnix() int64 {
	if x != nil {
		return x.ConfirmDeadlineUnix
	}
	return 0
}

type ConfirmTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTask) Reset() {
	*x = ConfirmTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTask) ProtoMessage() {}

func (x *ConfirmTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTask.ProtoReflect.Descriptor instead.
func (*ConfirmTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RollbackTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTask) Reset() {
	*x = RollbackTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTask) ProtoMessage() {}

func (x *RollbackTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTask.ProtoReflect.Descriptor instead.
func (*RollbackTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// SyncRequest asks the Agent to report its full current MYFW state so the
// Controller can reconcile after a reconnect.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_myfw_v1_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{10}
}

func (x *SyncRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnix        int64                  `protobuf:"varint,1,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_myfw_v1_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatAck) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

var File_myfw_v1_stream_proto protoreflect.FileDescriptor

const file_myfw_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x14myfw/v1/stream.proto\x12\amyfw.v1\x1a\x14myfw/v1/common.proto\x1a\x12myfw/v1/rule.proto\"\xe6\x01\n" +
	"\x11AgentToController\x122\n" +
	"\theartbeat\x18\x01 \x01(\v2\x12.myfw.v1.HeartbeatH\x00R\theartbeat\x126\n" +
	"\vtask_result\x18\x02 \x01(\v2\x13.myfw.v1.TaskResultH\x00R\n" +
	"taskResult\x12,\n" +
	"\x05drift\x18\x03 \x01(\v2\x14.myfw.v1.DriftReportH\x00R\x05drift\x12,\n" +
	"\x05state\x18\x04 \x01(\v2\x14.myfw.v1.StateReportH\x00R\x05stateB\t\n" +
	"\apayload\"\x95\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12!\n" +
	"\fcurrent_hash\x18\x03 \x01(\tR\vcurrentHash\x123\n" +
	"\n" +
	"capability\x18\x04 \x01(\v2\x13.myfw.v1.CapabilityR\n" +
	"capability\"\x89\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_hash\x18\x04 \x01(\tR\n" +
	"resultHash\x12\x17\n" +
	"\ats_unix\x18\x05 \x01(\x03R\x06tsUnix\"\x9d\x01\n" +
	"\vDriftReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rexpected_hash\x18\x02 \x01(\tR\fexpectedHash\x12\x1f\n" +
	"\vactual_hash\x18\x03 \x01(\tR\n" +
	"actualHash\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x17\n" +
	"\ats_unix\x18\x05 \x01(\x03R\x06tsUnix\"\xa0\x01\n" +
	"\vStateReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x126\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x16.myfw.v1.InterfaceStatR\n" +
	"interfaces\x12'\n" +
	"\x0fconntrack_count\x18\x04 \x01(\x04R\x0econntrackCount\"\x97\x01\n" +
	"\rInterfaceStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x04R\ttxPackets\"\x88\x02\n" +
	"\x11ControllerToAgent\x12*\n" +
	"\x05apply\x18\x01 \x01(\v2\x12.myfw.v1.ApplyTaskH\x00R\x05apply\x120\n" +
	"\aconfirm\x18\x02 \x01(\v2\x14.myfw.v1.ConfirmTaskH\x00R\aconfirm\x123\n" +
	"\brollback\x18\x03 \x01(\v2\x15.myfw.v1.RollbackTaskH\x00R\brollback\x12*\n" +
	"\x04sync\x18\x04 \x01(\v2\x14.myfw.v1.SyncRequestH\x00R\x04sync\x12)\n" +
	"\x03ack\x18\x05 \x01(\v2\x15.myfw.v1.HeartbeatAckH\x00R\x03ackB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\tApplyTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\brule_set\x18\x02 \x01(\v2\x10.myfw.v1.RuleSetR\aruleSet\x122\n" +
	"\x15confirm_deadline_unix\x18\x03 \x01(\x03R\x13confirmDeadlineUnix\"&\n" +
	"\vConfirmTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"'\n" +
	"\fRollbackTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"%\n" +
	"\vSyncRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"'\n" +
	"\fHeartbeatAck\x12\x17\n" +
	"\ats_unix\x18\x01 \x01(\x03R\x06tsUnix2T\n" +
	"\vAgentStream\x12E\n" +
	"\aConnect\x12\x1a.myfw.v1.AgentToController\x1a\x1a.myfw.v1.ControllerToAgent(\x010\x01B\"Z iptables-tool/api/myfw/v1;myfwv1b\x06proto3"

var (
	file_myfw_v1_stream_proto_rawDescOnce sync.Once
	file_myfw_v1_stream_proto_rawDescData []byte
)

func file_myfw_v1_stream_proto_rawDescGZIP() []byte {
	file_myfw_v1_stream_proto_rawDescOnce.Do(func() {
		file_myfw_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myfw_v1_stream_proto_rawDesc), len(file_myfw_v1_stream_proto_rawDesc)))
	})
	return file_myfw_v1_stream_proto_rawDescData
}

var file_myfw_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_myfw_v1_stream_proto_goTypes = []any{
	(*AgentToController)(nil), // 0: myfw.v1.AgentToController
	(*Heartbeat)(nil),         // 1: myfw.v1.Heartbeat
	(*TaskResult)(nil),        // 2: myfw.v1.TaskResult
	(*DriftReport)(nil),       // 3: myfw.v1.DriftReport
	(*StateReport)(nil),       // 4: myfw.v1.StateReport
	(*InterfaceStat)(nil),     // 5: myfw.v1.InterfaceStat
	(*ControllerToAgent)(nil), // 6: myfw.v1.ControllerToAgent
	(*ApplyTask)(nil),         // 7: myfw.v1.ApplyTask
	(*ConfirmTask)(nil),       // 8: myfw.v1.ConfirmTask
	(*RollbackTask)(nil),      // 9: myfw.v1.RollbackTask
	(*SyncRequest)(nil),       // 10: myfw.v1.SyncRequest
	(*HeartbeatAck)(nil),      // 11: myfw.v1.HeartbeatAck
	(*Capability)(nil),        // 12: myfw.v1.Capability
	(*RuleSet)(nil),           // 13: myfw.v1.RuleSet
}
var file_myfw_v1_stream_proto_depIdxs = []int32{
	1,  // 0: myfw.v1.AgentToController.heartbeat:type_name -> myfw.v1.Heartbeat
	2,  // 1: myfw.v1.AgentToController.task_result:type_name -> myfw.v1.TaskResult
	3,  // 2: myfw.v1.AgentToController.drift:type_name -> myfw.v1.DriftReport
	4,  // 3: myfw.v1.AgentToController.state:type_name -> myfw.v1.StateReport
	12, // 4: myfw.v1.Heartbeat.capability:type_name -> myfw.v1.Capability
	5,  // 5: myfw.v1.StateReport.interfaces:type_name -> myfw.v1.InterfaceStat
	7,  // 6: myfw.v1.ControllerToAgent.apply:type_name -> myfw.v1.ApplyTask
	8,  // 7: myfw.v1.ControllerToAgent.confirm:type_name -> myfw.v1.ConfirmTask
	9,  // 8: myfw.v1.ControllerToAgent.rollback:type_name -> myfw.v1.RollbackTask
	10, // 9: myfw.v1.ControllerToAgent.sync:type_name -> myfw.v1.SyncRequest
	11, // 10: myfw.v1.ControllerToAgent.ack:type_name -> myfw.v1.HeartbeatAck
	13, // 11: myfw.v1.ApplyTask.rule_set:type_name -> myfw.v1.RuleSet
	0,  // 12: myfw.v1.AgentStream.Connect:input_type -> myfw.v1.AgentToController
	6,  // 13: myfw.v1.AgentStream.Connect:output_type -> myfw.v1.ControllerToAgent
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_myfw_v1_stream_proto_init() }
func file_myfw_v1_stream_proto_init() {
	if File_myfw_v1_stream_proto != nil {
		return
	}
	file_myfw_v1_common_proto_init()
	file_myfw_v1_rule_proto_init()
	file_myfw_v1_stream_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentToController_Heartbeat)(nil),
		(*AgentToController_TaskResult)(nil),
		(*AgentToController_Drift)(nil),
		(*AgentToController_State)(nil),
	}
	file_myfw_v1_stream_proto_msgTypes[6].OneofWrappers = []any{
		(*ControllerToAgent_Apply)(nil),
		(*ControllerToAgent_Confirm)(nil),
		(*ControllerToAgent_Rollback)(nil),
		(*ControllerToAgent_Sync)(nil),
		(*ControllerToAgent_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myfw_v1_stream_proto_rawDesc), len(file_myfw_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myfw_v1_stream_proto_goTypes,
		DependencyIndexes: file_myfw_v1_stream_proto_depIdxs,
		MessageInfos:      file_myfw_v1_stream_proto_msgTypes,
	}.Build()
	File_myfw_v1_stream_proto = out.File
	file_myfw_v1_stream_proto_goTypes = nil
	file_myfw_v1_stream_proto_depIdxs = nil
}
