// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: myfw/v1/stream.proto

package myfwv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentStream_Connect_FullMethodName = "/myfw.v1.AgentStream/Connect"
)

// AgentStreamClient is the client API for AgentStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentStream is the single long-lived, mTLS-authenticated, bidirectional
// channel an ACTIVE Agent holds open to the Controller. The Agent dials the
// Controller (never the reverse) and multiplexes heartbeats, task dispatch,
// results, and state pushes over this stream. See design.md § 13.
type AgentStreamClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToController, ControllerToAgent], error)
}

type agentStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentStreamClient(cc grpc.ClientConnInterface) AgentStreamClient {
	return &agentStreamClient{cc}
}

func (c *agentStreamClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToController, ControllerToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentStream_ServiceDesc.Streams[0], AgentStream_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToController, ControllerToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_ConnectClient = grpc.BidiStreamingClient[AgentToController, ControllerToAgent]

// AgentStreamServer is the server API for AgentStream service.
// All implementations must embed UnimplementedAgentStreamServer
// for forward compatibility.
//
// AgentStream is the single long-lived, mTLS-authenticated, bidirectional
// channel an ACTIVE Agent holds open to the Controller. The Agent dials the
// Controller (never the reverse) and multiplexes heartbeats, task dispatch,
// results, and state pushes over this stream. See design.md § 13.
type AgentStreamServer interface {
	Connect(grpc.BidiStreamingServer[AgentToController, ControllerToAgent]) error
	mustEmbedUnimplementedAgentStreamServer()
}

// UnimplementedAgentStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentStreamServer struct{}

func (UnimplementedAgentStreamServer) Connect(grpc.BidiStreamingServer[AgentToController, ControllerToAgent]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentStreamServer) mustEmbedUnimplementedAgentStreamServer() {}
func (UnimplementedAgentStreamServer) testEmbeddedByValue()                     {}

// UnsafeAgentStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentStreamServer will
// result in compilation errors.
type UnsafeAgentStreamServer interface {
	mustEmbedUnimplementedAgentStreamServer()
}

func RegisterAgentStreamServer(s grpc.ServiceRegistrar, srv AgentStreamServer) {
	// If the following call panics, it indicates UnimplementedAgentStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentStream_ServiceDesc, srv)
}

func _AgentStream_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentStreamServer).Connect(&grpc.GenericServerStream[AgentToController, ControllerToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentStream_ConnectServer = grpc.BidiStreamingServer[AgentToController, ControllerToAgent]

// AgentStream_ServiceDesc is the grpc.ServiceDesc for AgentStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myfw.v1.AgentStream",
	HandlerType: (*AgentStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentStream_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "myfw/v1/stream.proto",
}
