// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: myfw/v1/stream.proto

package myfwv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleOpType 单条规则操作类型。
type RuleOpType int32

const (
	RuleOpType_RULE_OP_UNSPECIFIED RuleOpType = 0
	RuleOpType_RULE_OP_ADD         RuleOpType = 1 // 追加到链尾 (iptables -A)
	RuleOpType_RULE_OP_INSERT      RuleOpType = 2 // 插入到指定位置 (iptables -I)
	RuleOpType_RULE_OP_DELETE      RuleOpType = 3 // 删除 (iptables -D)
	RuleOpType_RULE_OP_REPLACE     RuleOpType = 4 // 替换 (iptables -R)
)

// Enum value maps for RuleOpType.
var (
	RuleOpType_name = map[int32]string{
		0: "RULE_OP_UNSPECIFIED",
		1: "RULE_OP_ADD",
		2: "RULE_OP_INSERT",
		3: "RULE_OP_DELETE",
		4: "RULE_OP_REPLACE",
	}
	RuleOpType_value = map[string]int32{
		"RULE_OP_UNSPECIFIED": 0,
		"RULE_OP_ADD":         1,
		"RULE_OP_INSERT":      2,
		"RULE_OP_DELETE":      3,
		"RULE_OP_REPLACE":     4,
	}
)

func (x RuleOpType) Enum() *RuleOpType {
	p := new(RuleOpType)
	*p = x
	return p
}

func (x RuleOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_myfw_v1_stream_proto_enumTypes[0].Descriptor()
}

func (RuleOpType) Type() protoreflect.EnumType {
	return &file_myfw_v1_stream_proto_enumTypes[0]
}

func (x RuleOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleOpType.Descriptor instead.
func (RuleOpType) EnumDescriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{0}
}

type AgentToController struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentToController_Heartbeat
	//	*AgentToController_TaskResult
	//	*AgentToController_Drift
	//	*AgentToController_State
	//	*AgentToController_Sync
	//	*AgentToController_IptablesRules
	Payload       isAgentToController_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToController) Reset() {
	*x = AgentToController{}
	mi := &file_myfw_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToController) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToController) ProtoMessage() {}

func (x *AgentToController) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToController.ProtoReflect.Descriptor instead.
func (*AgentToController) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToController) GetPayload() isAgentToController_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentToController) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToController) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentToController) GetDrift() *DriftReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Drift); ok {
			return x.Drift
		}
	}
	return nil
}

func (x *AgentToController) GetState() *StateReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *AgentToController) GetSync() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *AgentToController) GetIptablesRules() *IptablesRules {
	if x != nil {
		if x, ok := x.Payload.(*AgentToController_IptablesRules); ok {
			return x.IptablesRules
		}
	}
	return nil
}

type isAgentToController_Payload interface {
	isAgentToController_Payload()
}

type AgentToController_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentToController_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentToController_Drift struct {
	Drift *DriftReport `protobuf:"bytes,3,opt,name=drift,proto3,oneof"`
}

type AgentToController_State struct {
	State *StateReport `protobuf:"bytes,4,opt,name=state,proto3,oneof"`
}

type AgentToController_Sync struct {
	Sync *SyncRequest `protobuf:"bytes,5,opt,name=sync,proto3,oneof"`
}

type AgentToController_IptablesRules struct {
	IptablesRules *IptablesRules `protobuf:"bytes,6,opt,name=iptables_rules,json=iptablesRules,proto3,oneof"`
}

func (*AgentToController_Heartbeat) isAgentToController_Payload() {}

func (*AgentToController_TaskResult) isAgentToController_Payload() {}

func (*AgentToController_Drift) isAgentToController_Payload() {}

func (*AgentToController_State) isAgentToController_Payload() {}

func (*AgentToController_Sync) isAgentToController_Payload() {}

func (*AgentToController_IptablesRules) isAgentToController_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,3,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"` // hash of the live MYFW namespace
	Capability    *Capability            `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`                      // resent on change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_myfw_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *Heartbeat) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *Heartbeat) GetCapability() *Capability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResultHash    string                 `protobuf:"bytes,4,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"` // MYFW hash after applying
	TsUnix        int64                  `protobuf:"varint,5,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_myfw_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TaskResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResult) GetResultHash() string {
	if x != nil {
		return x.ResultHash
	}
	return ""
}

func (x *TaskResult) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

// DriftReport is emitted by the Watchdog when the live MYFW namespace no
// longer matches the expected hash (see design.md § 12).
type DriftReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	ActualHash    string                 `protobuf:"bytes,3,opt,name=actual_hash,json=actualHash,proto3" json:"actual_hash,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	TsUnix        int64                  `protobuf:"varint,5,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftReport) Reset() {
	*x = DriftReport{}
	mi := &file_myfw_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftReport) ProtoMessage() {}

func (x *DriftReport) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftReport.ProtoReflect.Descriptor instead.
func (*DriftReport) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *DriftReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DriftReport) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *DriftReport) GetActualHash() string {
	if x != nil {
		return x.ActualHash
	}
	return ""
}

func (x *DriftReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *DriftReport) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

// StateReport carries periodic network telemetry (see design.md § 14).
type StateReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TsUnix         int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Interfaces     []*InterfaceStat       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	ConntrackCount uint64                 `protobuf:"varint,4,opt,name=conntrack_count,json=conntrackCount,proto3" json:"conntrack_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateReport) Reset() {
	*x = StateReport{}
	mi := &file_myfw_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReport) ProtoMessage() {}

func (x *StateReport) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReport.ProtoReflect.Descriptor instead.
func (*StateReport) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StateReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateReport) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *StateReport) GetInterfaces() []*InterfaceStat {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *StateReport) GetConntrackCount() uint64 {
	if x != nil {
		return x.ConntrackCount
	}
	return 0
}

// IptablesRules 报告节点当前的 iptables 规则
type IptablesRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	Chains        []*IptablesChain       `protobuf:"bytes,3,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IptablesRules) Reset() {
	*x = IptablesRules{}
	mi := &file_myfw_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IptablesRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IptablesRules) ProtoMessage() {}

func (x *IptablesRules) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IptablesRules.ProtoReflect.Descriptor instead.
func (*IptablesRules) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *IptablesRules) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *IptablesRules) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *IptablesRules) GetChains() []*IptablesChain {
	if x != nil {
		return x.Chains
	}
	return nil
}

type IptablesChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"` // filter, nat, mangle, raw
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"` // INPUT, OUTPUT, FORWARD, etc.
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"` // iptables -S 输出的规则行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IptablesChain) Reset() {
	*x = IptablesChain{}
	mi := &file_myfw_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IptablesChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IptablesChain) ProtoMessage() {}

func (x *IptablesChain) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IptablesChain.ProtoReflect.Descriptor instead.
func (*IptablesChain) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{6}
}

func (x *IptablesChain) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *IptablesChain) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *IptablesChain) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type InterfaceStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStat) Reset() {
	*x = InterfaceStat{}
	mi := &file_myfw_v1_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStat) ProtoMessage() {}

func (x *InterfaceStat) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStat.ProtoReflect.Descriptor instead.
func (*InterfaceStat) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{7}
}

func (x *InterfaceStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStat) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceStat) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceStat) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceStat) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

type AgentStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent      float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsageBytes   int64                  `protobuf:"varint,2,opt,name=mem_usage_bytes,json=memUsageBytes,proto3" json:"mem_usage_bytes,omitempty"`
	MemTotalBytes   int64                  `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	ConnectionCount int64                  `protobuf:"varint,4,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	NetworkStats    []*NetworkStats        `protobuf:"bytes,5,rep,name=network_stats,json=networkStats,proto3" json:"network_stats,omitempty"`
	RuleHits        []*RuleHit             `protobuf:"bytes,6,rep,name=rule_hits,json=ruleHits,proto3" json:"rule_hits,omitempty"`
	Timestamp       *Timestamp             `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentStats) Reset() {
	*x = AgentStats{}
	mi := &file_myfw_v1_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStats) ProtoMessage() {}

func (x *AgentStats) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStats.ProtoReflect.Descriptor instead.
func (*AgentStats) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStats) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentStats) GetMemUsageBytes() int64 {
	if x != nil {
		return x.MemUsageBytes
	}
	return 0
}

func (x *AgentStats) GetMemTotalBytes() int64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *AgentStats) GetConnectionCount() int64 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *AgentStats) GetNetworkStats() []*NetworkStats {
	if x != nil {
		return x.NetworkStats
	}
	return nil
}

func (x *AgentStats) GetRuleHits() []*RuleHit {
	if x != nil {
		return x.RuleHits
	}
	return nil
}

func (x *AgentStats) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NetworkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     int64                  `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     int64                  `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_myfw_v1_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkStats) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkStats) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkStats) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkStats) GetRxPackets() int64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *NetworkStats) GetTxPackets() int64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

type RuleHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Hits          int64                  `protobuf:"varint,2,opt,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleHit) Reset() {
	*x = RuleHit{}
	mi := &file_myfw_v1_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleHit) ProtoMessage() {}

func (x *RuleHit) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleHit.ProtoReflect.Descriptor instead.
func (*RuleHit) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{10}
}

func (x *RuleHit) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleHit) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

type ControllerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerToAgent_Apply
	//	*ControllerToAgent_Confirm
	//	*ControllerToAgent_Rollback
	//	*ControllerToAgent_Sync
	//	*ControllerToAgent_Ack
	//	*ControllerToAgent_SyncRules
	//	*ControllerToAgent_RuleOperation
	//	*ControllerToAgent_ExecCommand
	//	*ControllerToAgent_RenewCert
	Payload       isControllerToAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerToAgent) Reset() {
	*x = ControllerToAgent{}
	mi := &file_myfw_v1_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerToAgent) ProtoMessage() {}

func (x *ControllerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerToAgent.ProtoReflect.Descriptor instead.
func (*ControllerToAgent) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{11}
}

func (x *ControllerToAgent) GetPayload() isControllerToAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerToAgent) GetApply() *ApplyTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *ControllerToAgent) GetConfirm() *ConfirmTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *ControllerToAgent) GetRollback() *RollbackTask {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *ControllerToAgent) GetSync() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *ControllerToAgent) GetAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControllerToAgent) GetSyncRules() *SyncRulesRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_SyncRules); ok {
			return x.SyncRules
		}
	}
	return nil
}

func (x *ControllerToAgent) GetRuleOperation() *RuleOperation {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_RuleOperation); ok {
			return x.RuleOperation
		}
	}
	return nil
}

func (x *ControllerToAgent) GetExecCommand() *ExecCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_ExecCommand); ok {
			return x.ExecCommand
		}
	}
	return nil
}

func (x *ControllerToAgent) GetRenewCert() *RenewCertCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControllerToAgent_RenewCert); ok {
			return x.RenewCert
		}
	}
	return nil
}

type isControllerToAgent_Payload interface {
	isControllerToAgent_Payload()
}

type ControllerToAgent_Apply struct {
	Apply *ApplyTask `protobuf:"bytes,1,opt,name=apply,proto3,oneof"`
}

type ControllerToAgent_Confirm struct {
	Confirm *ConfirmTask `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

type ControllerToAgent_Rollback struct {
	Rollback *RollbackTask `protobuf:"bytes,3,opt,name=rollback,proto3,oneof"`
}

type ControllerToAgent_Sync struct {
	Sync *SyncRequest `protobuf:"bytes,4,opt,name=sync,proto3,oneof"`
}

type ControllerToAgent_Ack struct {
	Ack *HeartbeatAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type ControllerToAgent_SyncRules struct {
	SyncRules *SyncRulesRequest `protobuf:"bytes,6,opt,name=sync_rules,json=syncRules,proto3,oneof"`
}

type ControllerToAgent_RuleOperation struct {
	RuleOperation *RuleOperation `protobuf:"bytes,7,opt,name=rule_operation,json=ruleOperation,proto3,oneof"`
}

type ControllerToAgent_ExecCommand struct {
	ExecCommand *ExecCommand `protobuf:"bytes,8,opt,name=exec_command,json=execCommand,proto3,oneof"` // 专家模式:裸 iptables 命令
}

type ControllerToAgent_RenewCert struct {
	RenewCert *RenewCertCommand `protobuf:"bytes,9,opt,name=renew_cert,json=renewCert,proto3,oneof"` // 触发 Agent 证书续签
}

func (*ControllerToAgent_Apply) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Confirm) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Rollback) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Sync) isControllerToAgent_Payload() {}

func (*ControllerToAgent_Ack) isControllerToAgent_Payload() {}

func (*ControllerToAgent_SyncRules) isControllerToAgent_Payload() {}

func (*ControllerToAgent_RuleOperation) isControllerToAgent_Payload() {}

func (*ControllerToAgent_ExecCommand) isControllerToAgent_Payload() {}

func (*ControllerToAgent_RenewCert) isControllerToAgent_Payload() {}

// SyncRulesRequest 请求 Agent 上报当前 iptables 规则
type SyncRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRulesRequest) Reset() {
	*x = SyncRulesRequest{}
	mi := &file_myfw_v1_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRulesRequest) ProtoMessage() {}

func (x *SyncRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRulesRequest.ProtoReflect.Descriptor instead.
func (*SyncRulesRequest) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{12}
}

func (x *SyncRulesRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RuleOperation 下发单条规则操作到 Agent（节点规则页增删改插）。
// 双模式：
//   - 专家模式：rule_line 给出 iptables-save 格式规则体（如 "-p tcp --dport 80 -j ACCEPT"）
//   - 结构化模式：rule_line 为空时，由 action/protocol/source/destination/port 翻译
type RuleOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"` // filter/nat/mangle/raw
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"` // INPUT/OUTPUT/FORWARD/...
	Op            RuleOpType             `protobuf:"varint,4,opt,name=op,proto3,enum=myfw.v1.RuleOpType" json:"op,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`                // 插入/替换位置（1-based），0 表示追加
	RuleLine      string                 `protobuf:"bytes,6,opt,name=rule_line,json=ruleLine,proto3" json:"rule_line,omitempty"` // 专家模式：原始规则体
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`                     // ACCEPT/DROP/REJECT/MARK/DNAT/SNAT
	Protocol      string                 `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`                 // tcp/udp/icmp/any
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`                     // 源 IP/CIDR
	Destination   string                 `protobuf:"bytes,10,opt,name=destination,proto3" json:"destination,omitempty"`          // 目的 IP/CIDR
	Port          string                 `protobuf:"bytes,11,opt,name=port,proto3" json:"port,omitempty"`                        // 端口或范围
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleOperation) Reset() {
	*x = RuleOperation{}
	mi := &file_myfw_v1_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleOperation) ProtoMessage() {}

func (x *RuleOperation) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleOperation.ProtoReflect.Descriptor instead.
func (*RuleOperation) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{13}
}

func (x *RuleOperation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RuleOperation) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RuleOperation) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *RuleOperation) GetOp() RuleOpType {
	if x != nil {
		return x.Op
	}
	return RuleOpType_RULE_OP_UNSPECIFIED
}

func (x *RuleOperation) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RuleOperation) GetRuleLine() string {
	if x != nil {
		return x.RuleLine
	}
	return ""
}

func (x *RuleOperation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RuleOperation) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RuleOperation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RuleOperation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RuleOperation) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

// ExecCommand 专家模式:下发裸 iptables 命令到 Agent 执行。
// command 为完整命令(如 "iptables -t nat -L -n"、"iptables-save -t filter"),
// Agent 侧校验首 token 必须属于 iptables 族白名单,执行后回 TaskResult。
// 注意:此通道绕过 MYFW 命名空间/快照/保护期,仅供高级管理员排障,强审计留痕。
type ExecCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // 完整裸命令(iptables 族)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommand) Reset() {
	*x = ExecCommand{}
	mi := &file_myfw_v1_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommand) ProtoMessage() {}

func (x *ExecCommand) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommand.ProtoReflect.Descriptor instead.
func (*ExecCommand) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{14}
}

func (x *ExecCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// RenewCertCommand 触发 Agent 立即续签客户端证书。续签由 Agent 用旧证书
// 发起 CSR（Controller 无法替 Agent 续签），成功后 Agent 重建连接加载新证书。
type RenewCertCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertCommand) Reset() {
	*x = RenewCertCommand{}
	mi := &file_myfw_v1_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertCommand) ProtoMessage() {}

func (x *RenewCertCommand) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertCommand.ProtoReflect.Descriptor instead.
func (*RenewCertCommand) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{15}
}

// ApplyTask instructs the Agent to snapshot, then converge its MYFW namespace
// to the given RuleSet, then wait for a ConfirmTask within confirm_deadline
// (else auto-rollback). See design.md § 11.
type ApplyTask struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RuleSet             *RuleSet               `protobuf:"bytes,2,opt,name=rule_set,json=ruleSet,proto3" json:"rule_set,omitempty"`
	ConfirmDeadlineUnix int64                  `protobuf:"varint,3,opt,name=confirm_deadline_unix,json=confirmDeadlineUnix,proto3" json:"confirm_deadline_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ApplyTask) Reset() {
	*x = ApplyTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTask) ProtoMessage() {}

func (x *ApplyTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTask.ProtoReflect.Descriptor instead.
func (*ApplyTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApplyTask) GetRuleSet() *RuleSet {
	if x != nil {
		return x.RuleSet
	}
	return nil
}

func (x *ApplyTask) GetConfirmDeadlineUnix() int64 {
	if x != nil {
		return x.ConfirmDeadlineUnix
	}
	return 0
}

type ConfirmTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTask) Reset() {
	*x = ConfirmTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTask) ProtoMessage() {}

func (x *ConfirmTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTask.ProtoReflect.Descriptor instead.
func (*ConfirmTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RollbackTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTask) Reset() {
	*x = RollbackTask{}
	mi := &file_myfw_v1_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTask) ProtoMessage() {}

func (x *RollbackTask) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTask.ProtoReflect.Descriptor instead.
func (*RollbackTask) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{18}
}

func (x *RollbackTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// SyncRequest asks the Agent to report its full current MYFW state so the
// Controller can reconcile after a reconnect.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_myfw_v1_stream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{19}
}

func (x *SyncRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnix        int64                  `protobuf:"varint,1,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_myfw_v1_stream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_myfw_v1_stream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_myfw_v1_stream_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatAck) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

var File_myfw_v1_stream_proto protoreflect.FileDescriptor

const file_myfw_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x14myfw/v1/stream.proto\x12\amyfw.v1\x1a\x14myfw/v1/common.proto\x1a\x12myfw/v1/rule.proto\"\xd3\x02\n" +
	"\x11AgentToController\x122\n" +
	"\theartbeat\x18\x01 \x01(\v2\x12.myfw.v1.HeartbeatH\x00R\theartbeat\x126\n" +
	"\vtask_result\x18\x02 \x01(\v2\x13.myfw.v1.TaskResultH\x00R\n" +
	"taskResult\x12,\n" +
	"\x05drift\x18\x03 \x01(\v2\x14.myfw.v1.DriftReportH\x00R\x05drift\x12,\n" +
	"\x05state\x18\x04 \x01(\v2\x14.myfw.v1.StateReportH\x00R\x05state\x12*\n" +
	"\x04sync\x18\x05 \x01(\v2\x14.myfw.v1.SyncRequestH\x00R\x04sync\x12?\n" +
	"\x0eiptables_rules\x18\x06 \x01(\v2\x16.myfw.v1.IptablesRulesH\x00R\riptablesRulesB\t\n" +
	"\apayload\"\x95\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12!\n" +
	"\fcurrent_hash\x18\x03 \x01(\tR\vcurrentHash\x123\n" +
	"\n" +
	"capability\x18\x04 \x01(\v2\x13.myfw.v1.CapabilityR\n" +
	"capability\"\x89\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_hash\x18\x04 \x01(\tR\n" +
	"resultHash\x12\x17\n" +
	"\ats_unix\x18\x05 \x01(\x03R\x06tsUnix\"\x9d\x01\n" +
	"\vDriftReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rexpected_hash\x18\x02 \x01(\tR\fexpectedHash\x12\x1f\n" +
	"\vactual_hash\x18\x03 \x01(\tR\n" +
	"actualHash\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x17\n" +
	"\ats_unix\x18\x05 \x01(\x03R\x06tsUnix\"\xa0\x01\n" +
	"\vStateReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x126\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x16.myfw.v1.InterfaceStatR\n" +
	"interfaces\x12'\n" +
	"\x0fconntrack_count\x18\x04 \x01(\x04R\x0econntrackCount\"q\n" +
	"\rIptablesRules\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12.\n" +
	"\x06chains\x18\x03 \x03(\v2\x16.myfw.v1.IptablesChainR\x06chains\"Q\n" +
	"\rIptablesChain\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"\x97\x01\n" +
	"\rInterfaceStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x04R\ttxPackets\"\xc5\x02\n" +
	"\n" +
	"AgentStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12&\n" +
	"\x0fmem_usage_bytes\x18\x02 \x01(\x03R\rmemUsageBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x03R\rmemTotalBytes\x12)\n" +
	"\x10connection_count\x18\x04 \x01(\x03R\x0fconnectionCount\x12:\n" +
	"\rnetwork_stats\x18\x05 \x03(\v2\x15.myfw.v1.NetworkStatsR\fnetworkStats\x12-\n" +
	"\trule_hits\x18\x06 \x03(\v2\x10.myfw.v1.RuleHitR\bruleHits\x120\n" +
	"\ttimestamp\x18\a \x01(\v2\x12.myfw.v1.TimestampR\ttimestamp\"\xa0\x01\n" +
	"\fNetworkStats\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x03R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x03R\ttxPackets\"6\n" +
	"\aRuleHit\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04hits\x18\x02 \x01(\x03R\x04hits\"\xfc\x03\n" +
	"\x11ControllerToAgent\x12*\n" +
	"\x05apply\x18\x01 \x01(\v2\x12.myfw.v1.ApplyTaskH\x00R\x05apply\x120\n" +
	"\aconfirm\x18\x02 \x01(\v2\x14.myfw.v1.ConfirmTaskH\x00R\aconfirm\x123\n" +
	"\brollback\x18\x03 \x01(\v2\x15.myfw.v1.RollbackTaskH\x00R\brollback\x12*\n" +
	"\x04sync\x18\x04 \x01(\v2\x14.myfw.v1.SyncRequestH\x00R\x04sync\x12)\n" +
	"\x03ack\x18\x05 \x01(\v2\x15.myfw.v1.HeartbeatAckH\x00R\x03ack\x12:\n" +
	"\n" +
	"sync_rules\x18\x06 \x01(\v2\x19.myfw.v1.SyncRulesRequestH\x00R\tsyncRules\x12?\n" +
	"\x0erule_operation\x18\a \x01(\v2\x16.myfw.v1.RuleOperationH\x00R\rruleOperation\x129\n" +
	"\fexec_command\x18\b \x01(\v2\x14.myfw.v1.ExecCommandH\x00R\vexecCommand\x12:\n" +
	"\n" +
	"renew_cert\x18\t \x01(\v2\x19.myfw.v1.RenewCertCommandH\x00R\trenewCertB\t\n" +
	"\apayload\"*\n" +
	"\x10SyncRulesRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xb4\x02\n" +
	"\rRuleOperation\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12#\n" +
	"\x02op\x18\x04 \x01(\x0e2\x13.myfw.v1.RuleOpTypeR\x02op\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1b\n" +
	"\trule_line\x18\x06 \x01(\tR\bruleLine\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\n" +
	" \x01(\tR\vdestination\x12\x12\n" +
	"\x04port\x18\v \x01(\tR\x04port\"@\n" +
	"\vExecCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\x12\n" +
	"\x10RenewCertCommand\"\x85\x01\n" +
	"\tApplyTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\brule_set\x18\x02 \x01(\v2\x10.myfw.v1.RuleSetR\aruleSet\x122\n" +
	"\x15confirm_deadline_unix\x18\x03 \x01(\x03R\x13confirmDeadlineUnix\"&\n" +
	"\vConfirmTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"'\n" +
	"\fRollbackTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"%\n" +
	"\vSyncRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"'\n" +
	"\fHeartbeatAck\x12\x17\n" +
	"\ats_unix\x18\x01 \x01(\x03R\x06tsUnix*s\n" +
	"\n" +
	"RuleOpType\x12\x17\n" +
	"\x13RULE_OP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRULE_OP_ADD\x10\x01\x12\x12\n" +
	"\x0eRULE_OP_INSERT\x10\x02\x12\x12\n" +
	"\x0eRULE_OP_DELETE\x10\x03\x12\x13\n" +
	"\x0fRULE_OP_REPLACE\x10\x042T\n" +
	"\vAgentStream\x12E\n" +
	"\aConnect\x12\x1a.myfw.v1.AgentToController\x1a\x1a.myfw.v1.ControllerToAgent(\x010\x01B\"Z iptables-tool/api/myfw/v1;myfwv1b\x06proto3"

var (
	file_myfw_v1_stream_proto_rawDescOnce sync.Once
	file_myfw_v1_stream_proto_rawDescData []byte
)

func file_myfw_v1_stream_proto_rawDescGZIP() []byte {
	file_myfw_v1_stream_proto_rawDescOnce.Do(func() {
		file_myfw_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myfw_v1_stream_proto_rawDesc), len(file_myfw_v1_stream_proto_rawDesc)))
	})
	return file_myfw_v1_stream_proto_rawDescData
}

var file_myfw_v1_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_myfw_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_myfw_v1_stream_proto_goTypes = []any{
	(RuleOpType)(0),           // 0: myfw.v1.RuleOpType
	(*AgentToController)(nil), // 1: myfw.v1.AgentToController
	(*Heartbeat)(nil),         // 2: myfw.v1.Heartbeat
	(*TaskResult)(nil),        // 3: myfw.v1.TaskResult
	(*DriftReport)(nil),       // 4: myfw.v1.DriftReport
	(*StateReport)(nil),       // 5: myfw.v1.StateReport
	(*IptablesRules)(nil),     // 6: myfw.v1.IptablesRules
	(*IptablesChain)(nil),     // 7: myfw.v1.IptablesChain
	(*InterfaceStat)(nil),     // 8: myfw.v1.InterfaceStat
	(*AgentStats)(nil),        // 9: myfw.v1.AgentStats
	(*NetworkStats)(nil),      // 10: myfw.v1.NetworkStats
	(*RuleHit)(nil),           // 11: myfw.v1.RuleHit
	(*ControllerToAgent)(nil), // 12: myfw.v1.ControllerToAgent
	(*SyncRulesRequest)(nil),  // 13: myfw.v1.SyncRulesRequest
	(*RuleOperation)(nil),     // 14: myfw.v1.RuleOperation
	(*ExecCommand)(nil),       // 15: myfw.v1.ExecCommand
	(*RenewCertCommand)(nil),  // 16: myfw.v1.RenewCertCommand
	(*ApplyTask)(nil),         // 17: myfw.v1.ApplyTask
	(*ConfirmTask)(nil),       // 18: myfw.v1.ConfirmTask
	(*RollbackTask)(nil),      // 19: myfw.v1.RollbackTask
	(*SyncRequest)(nil),       // 20: myfw.v1.SyncRequest
	(*HeartbeatAck)(nil),      // 21: myfw.v1.HeartbeatAck
	(*Capability)(nil),        // 22: myfw.v1.Capability
	(*Timestamp)(nil),         // 23: myfw.v1.Timestamp
	(*RuleSet)(nil),           // 24: myfw.v1.RuleSet
}
var file_myfw_v1_stream_proto_depIdxs = []int32{
	2,  // 0: myfw.v1.AgentToController.heartbeat:type_name -> myfw.v1.Heartbeat
	3,  // 1: myfw.v1.AgentToController.task_result:type_name -> myfw.v1.TaskResult
	4,  // 2: myfw.v1.AgentToController.drift:type_name -> myfw.v1.DriftReport
	5,  // 3: myfw.v1.AgentToController.state:type_name -> myfw.v1.StateReport
	20, // 4: myfw.v1.AgentToController.sync:type_name -> myfw.v1.SyncRequest
	6,  // 5: myfw.v1.AgentToController.iptables_rules:type_name -> myfw.v1.IptablesRules
	22, // 6: myfw.v1.Heartbeat.capability:type_name -> myfw.v1.Capability
	8,  // 7: myfw.v1.StateReport.interfaces:type_name -> myfw.v1.InterfaceStat
	7,  // 8: myfw.v1.IptablesRules.chains:type_name -> myfw.v1.IptablesChain
	10, // 9: myfw.v1.AgentStats.network_stats:type_name -> myfw.v1.NetworkStats
	11, // 10: myfw.v1.AgentStats.rule_hits:type_name -> myfw.v1.RuleHit
	23, // 11: myfw.v1.AgentStats.timestamp:type_name -> myfw.v1.Timestamp
	17, // 12: myfw.v1.ControllerToAgent.apply:type_name -> myfw.v1.ApplyTask
	18, // 13: myfw.v1.ControllerToAgent.confirm:type_name -> myfw.v1.ConfirmTask
	19, // 14: myfw.v1.ControllerToAgent.rollback:type_name -> myfw.v1.RollbackTask
	20, // 15: myfw.v1.ControllerToAgent.sync:type_name -> myfw.v1.SyncRequest
	21, // 16: myfw.v1.ControllerToAgent.ack:type_name -> myfw.v1.HeartbeatAck
	13, // 17: myfw.v1.ControllerToAgent.sync_rules:type_name -> myfw.v1.SyncRulesRequest
	14, // 18: myfw.v1.ControllerToAgent.rule_operation:type_name -> myfw.v1.RuleOperation
	15, // 19: myfw.v1.ControllerToAgent.exec_command:type_name -> myfw.v1.ExecCommand
	16, // 20: myfw.v1.ControllerToAgent.renew_cert:type_name -> myfw.v1.RenewCertCommand
	0,  // 21: myfw.v1.RuleOperation.op:type_name -> myfw.v1.RuleOpType
	24, // 22: myfw.v1.ApplyTask.rule_set:type_name -> myfw.v1.RuleSet
	1,  // 23: myfw.v1.AgentStream.Connect:input_type -> myfw.v1.AgentToController
	12, // 24: myfw.v1.AgentStream.Connect:output_type -> myfw.v1.ControllerToAgent
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_myfw_v1_stream_proto_init() }
func file_myfw_v1_stream_proto_init() {
	if File_myfw_v1_stream_proto != nil {
		return
	}
	file_myfw_v1_common_proto_init()
	file_myfw_v1_rule_proto_init()
	file_myfw_v1_stream_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentToController_Heartbeat)(nil),
		(*AgentToController_TaskResult)(nil),
		(*AgentToController_Drift)(nil),
		(*AgentToController_State)(nil),
		(*AgentToController_Sync)(nil),
		(*AgentToController_IptablesRules)(nil),
	}
	file_myfw_v1_stream_proto_msgTypes[11].OneofWrappers = []any{
		(*ControllerToAgent_Apply)(nil),
		(*ControllerToAgent_Confirm)(nil),
		(*ControllerToAgent_Rollback)(nil),
		(*ControllerToAgent_Sync)(nil),
		(*ControllerToAgent_Ack)(nil),
		(*ControllerToAgent_SyncRules)(nil),
		(*ControllerToAgent_RuleOperation)(nil),
		(*ControllerToAgent_ExecCommand)(nil),
		(*ControllerToAgent_RenewCert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myfw_v1_stream_proto_rawDesc), len(file_myfw_v1_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myfw_v1_stream_proto_goTypes,
		DependencyIndexes: file_myfw_v1_stream_proto_depIdxs,
		EnumInfos:         file_myfw_v1_stream_proto_enumTypes,
		MessageInfos:      file_myfw_v1_stream_proto_msgTypes,
	}.Build()
	File_myfw_v1_stream_proto = out.File
	file_myfw_v1_stream_proto_goTypes = nil
	file_myfw_v1_stream_proto_depIdxs = nil
}
